# Generated by Django 4.2.7 on 2023-11-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
