# Generated by Django 4.2.7 on 2023-11-14 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_instance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='collection_instance',
            name='collected_revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.revenue', to_field='revenue_type'),
        ),
        migrations.AlterField(
            model_name='collection_instance',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue_type',
            field=models.CharField(choices=[('Market Fee', 'market fee'), ('Business Tax', 'business tax'), ('City Rate', 'city rate'), ('License Fee', 'license fee')], max_length=150, unique=True),
        ),
    ]
