# Generated by Django 4.2.7 on 2023-11-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50, unique=True)),
                ('land_use', models.CharField(choices=[('Domestic', 'Domestic'), ('Commercial', 'Commercial')], max_length=20)),
                ('capital_value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('name', models.CharField(max_length=150)),
                ('rates_owed', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
