# Generated by Django 4.2.7 on 2023-11-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_about_remove_newuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('councilID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Council',
                'verbose_name_plural': 'Councils',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.council')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receipt_info', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=150)),
                ('collectorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_id', to=settings.AUTH_USER_MODEL)),
                ('councilID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.council')),
                ('payerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_id', to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.council')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issueID', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=150)),
                ('resolution_details', models.CharField(max_length=150)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=150)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('tax_details', models.CharField(max_length=150)),
                ('OwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('councilID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.council')),
            ],
        ),
    ]
