# Generated by Django 4.2.7 on 2023-11-20 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_instance',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
