# Generated by Django 4.2.7 on 2023-11-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_alter_collection_instance_collector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_instance',
            name='name',
        ),
        migrations.CreateModel(
            name='CollectionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('collection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.collectiontype')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collector')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
            ],
        ),
    ]
