# Generated by Django 4.2.7 on 2023-11-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_council_service_transaction_notification_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='council',
            options={},
        ),
    ]
