# Generated by Django 4.2.7 on 2023-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_collection_instance_id_transaction_collection_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
