# Generated by Django 4.2.7 on 2023-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_collection_instance_name_collectioninstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninstance',
            name='amount',
            field=models.CharField(max_length=60),
        ),
    ]
