# Generated by Django 4.2.7 on 2023-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='revenue_type',
            field=models.CharField(choices=[('Market Fee', 'market fee'), ('Business Tax', 'business tax'), ('City Rate', 'city rate'), ('License Fee', 'license fee'), ('Parking Fee', 'parking fee')], max_length=150, unique=True),
        ),
    ]
