# Generated by Django 4.2.7 on 2023-11-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_revenue_revenue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
