# Generated by Django 4.2.7 on 2023-11-22 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], max_length=150)),
                ('description', models.TextField()),
                ('collection_instance_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.collection_instance')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.revenue')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
