# Generated by Django 4.2.7 on 2023-11-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection_instance',
            old_name='collected_revenue',
            new_name='type_to_collect',
        ),
        migrations.RemoveField(
            model_name='collection_instance',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='collection_instance',
            name='name',
        ),
        migrations.AddField(
            model_name='collection_instance',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
